import { Property } from "@/types";

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Property", href: "/properties" },
  { label: "Approvals", href: "/approvals" },
  { label: "Contact", href: "/contact" },
];

export const HERO_STATS = [
  { value: "50K+", label: "Happy Clients" },
  { value: "200+", label: "Properties" },
  { value: "4.5", label: "Rating" },
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "1",
    title: "Spacious & Luxurious in Dubai",
    location: "Downtown, Dubai, UAE",
    price: 7500,
    beds: 4, baths: 2, sqft: 1150,
    category: "House",
    status: "For Sale",
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80",
    postedAt: "6 months ago",
  },
  {
    id: "2",
    title: "Spacious & Luxurious in Dubai",
    location: "Downtown, Dubai, UAE",
    price: 7500,
    beds: 4, baths: 2, sqft: 1150,
    category: "Villa",
    status: "For Sale",
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",
    postedAt: "1 years ago",
  },
  {
    id: "3",
    title: "Spacious & Luxurious in Dubai",
    location: "Downtown, Dubai, UAE",
    price: 7500,
    beds: 4, baths: 2, sqft: 1150,
    category: "House",
    status: "For Sale",
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=600&q=80",
    postedAt: "1 months ago",
  },
  {
    id: "4",
    title: "Spacious & Luxurious in Dubai",
    location: "Downtown, Dubai, UAE",
    price: 7500,
    beds: 4, baths: 2, sqft: 1150,
    category: "Apartment",
    status: "For Sale",
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80",
    postedAt: "3 months ago",
  },
  {
    id: "5",
    title: "Spacious & Luxurious in Dubai",
    location: "Downtown, Dubai, UAE",
    price: 7500,
    beds: 4, baths: 2, sqft: 1150,
    category: "Villa",
    status: "For Sale",
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&q=80",
    postedAt: "2 months ago",
  },
  {
    id: "6",
    title: "Spacious & Luxurious in Dubai",
    location: "Downtown, Dubai, UAE",
    price: 7500,
    beds: 4, baths: 2, sqft: 1150,
    category: "Apartment",
    status: "For Sale",
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80",
    postedAt: "5 months ago",
  },
  {
    id: "7",
    title: "Spacious & Luxurious in Dubai",
    location: "Downtown, Dubai, UAE",
    price: 7500,
    beds: 4, baths: 2, sqft: 1150,
    category: "House",
    status: "For Sale",
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&q=80",
    postedAt: "4 months ago",
  },
  {
    id: "8",
    title: "Spacious & Luxurious in Dubai",
    location: "Downtown, Dubai, UAE",
    price: 7500,
    beds: 4, baths: 2, sqft: 1150,
    category: "Villa",
    status: "For Sale",
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=600&q=80",
    postedAt: "7 months ago",
  },
];
